### PR TITLE
Add option --sudo

### PR DESCRIPTION
**Pull request by jocelynj**
This will launch the following commands with sudo:

  - pct/qm commands
  - cat /etc/pve/.vmlist

### CODE REVIEW

**Comment by apprell** [comment]
Hi,

Can you tell me what this is for?

The script needs to be run 100% from a privileged user, and it's easier to run the script itself with `sudo -u autosnapuser proxmox-autosnap.py` if needed

**Comment by jocelynj** [comment]
I've added this option to run the script as a specific user, and limit the specific commands that are launched as root. I think it also allows to make sure that the script doesn't launch any other command if there is a mistake in the python code.

What is your proposition of `sudo -u autosnapuser proxmox-autosnap.py`? Would this account autosnapuser be a privileged user with root permissions?

**Comment by apprell** [comment]
Can you show what rules for the user who will run the script you used for the tests `sudo -l -U <username>`?

**Comment by jocelynj** [comment]
Here is the list I have:
```
proxmox-backup ALL=NOPASSWD: /usr/bin/cat /etc/pve/.vmlist, /usr/sbin/pct snapshot *, /usr/sbin/pct listsnapshot *, /usr/sbin/pct delsnapshot *
```
By the way, I would totally understand if you don't want to merge this PR to your repository :)

**Comment by apprell** [comment]
Cleaned up the script and added sudo, so the new code has everything you need

**Comment by jocelynj** [comment]
Thanks, this looks good.

**Pull request closed without merging**
