### PR TITLE
Add option --zfs-send-to to send zfs snapshot to another host

### PR DESCRIPTION
**Pull request by jocelynj**
Linked to discussion on #6.

### CODE REVIEW

**Comment by jocelynj** [comment]
I’m not 100% happy with the `backup=0/1` stuff, but it looks like that Proxmox encodes this value differently for VM and LXC.

**Comment by apprell** [comment]
What about ide (for example, it is needed for Mikrotik version 6) and efidisk?

**Comment by jocelynj** [comment]
I will replace `scsi` by `(ide|sata|scsi|virtio)`, but I will be able to test only scsi.

**Comment by jocelynj** [comment]
For `efidisk`, do you know how proxmox handle the `backup=0/1` part?
Should we also add `tpmstate`: https://pve.proxmox.com/pve-docs/chapter-qm.html#qm_tpm?

**Comment by apprell** [comment]
Checked options for disabling backups for efidisk and tmpstate partitions are not present. Verified if Proxmox Backup Server includes these partitions in backups, and they are present in the backup.

image

**Pull request merged**
